# Generated by Django 6.0.1 on 2026-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('badge', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='templates/')),
                ('description', models.TextField()),
            ],
        ),
    ]
