# Generated by Django 6.0.5 on 2026-05-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('downloads', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='motion/thumbnails/')),
                ('video', models.FileField(upload_to='motion/videos/')),
                ('description', models.TextField()),
            ],
        ),
    ]
