# Generated by Django 6.0.5 on 2026-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0003_motion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('template', 'Template'), ('video', 'Video'), ('motion', 'Motion Graphics')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/thumbnails/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='assets/previews/')),
                ('zip_file', models.FileField(upload_to='assets/zips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
