# Generated by Django 6.0.5 on 2026-06-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0004_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='rating',
        ),
    ]
