# Generated by Django 6.0.5 on 2026-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0005_remove_asset_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
