# Generated by Django 6.0.1 on 2026-06-16 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0008_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assetrating',
            name='guest_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetrating',
            constraint=models.UniqueConstraint(fields=('asset', 'user'), name='unique_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='assetrating',
            constraint=models.UniqueConstraint(fields=('asset', 'guest_ip'), name='unique_guest_rating'),
        ),
    ]
